# Generated by Django 4.0.4 on 2022-06-08 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Автоматически задается при создании', verbose_name='Дата и время создания')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Автоматически задается при изменении', verbose_name='Дата и время изменения')),
                ('name', models.CharField(help_text='Наименование группы продукта/услуги в каталоге', max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Группа продукта/услуги',
                'verbose_name_plural': 'Группы продукта/услуги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Автоматически задается при создании', verbose_name='Дата и время создания')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Автоматически задается при изменении', verbose_name='Дата и время изменения')),
                ('name', models.CharField(help_text='Наименование единицы измерения', max_length=50, verbose_name='Наименование')),
                ('short_name', models.CharField(help_text='Сокращенное наименование единицы измерения', max_length=10, verbose_name='Сокращенное наименование')),
                ('code', models.CharField(help_text='Код единицы измерения (напр. PCE - штука, MIN - минута)', max_length=10, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Автоматически задается при создании', verbose_name='Дата и время создания')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Автоматически задается при изменении', verbose_name='Дата и время изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('name', models.CharField(help_text='Наименование продукта/услуги в каталоге', max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, help_text='Описание продукта/услуги в каталоге', verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Розничная цена по каталогу', max_digits=12, verbose_name='Цена')),
                ('group', models.ManyToManyField(blank=True, help_text='Группы продукта/услуги в каталоге', related_name='products', to='catalog.groupproduct', verbose_name='Группы')),
                ('unit', models.ForeignKey(help_text='Единица измерения продукта/услуги в каталоге', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.unit', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Продукт/услуга каталога',
                'verbose_name_plural': 'Продукты/услуги каталога',
                'ordering': ['name'],
            },
        ),
    ]
