# Generated by Django 4.0.4 on 2022-05-19 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование типа компании (напр. Поставщик, Клиент и т.п.)', max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': ('Тип компании',),
                'verbose_name_plural': 'Типы компаний',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(help_text='Индивидуальный номер налогоплательщика компании', max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, help_text='Код причины постановки', max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(help_text='Основной государственный регистрационный номер компании', max_length=15, verbose_name='ОГРН/ОГРНИП')),
                ('short_name', models.CharField(help_text='Краткое наименование организации (напр. ООО "УП", ИП "Петров И.И.")', max_length=255, verbose_name='Краткое наименование организации')),
                ('full_name', models.CharField(help_text='Полное наименование организации (напр. Общество с ограниченной ответственностью "Универсальное предприятие", Индивидуальный предприниматель "Петров И.И.")', max_length=255, verbose_name='Полное наименование организации')),
                ('date_reg', models.DateField(help_text='Дата государственной регистрации компании', verbose_name='Дата государственной регистрации')),
                ('position_director', models.CharField(default='Директор', help_text='Наименование должности руководителя компании (напр. Директор, Генеральный директор и т.п.', max_length=50, verbose_name='Должность руководителя')),
                ('name_director', models.CharField(help_text='Фамилия, имя, отчество руководителя компании', max_length=255, verbose_name='Руководитель')),
                ('legal_address', models.CharField(help_text='Юридический адрес компании', max_length=255, verbose_name='Юридический адрес')),
            ],
            options={
                'verbose_name': ('Реквизиты',),
                'verbose_name_plural': 'Реквизиты',
                'ordering': ['inn'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование компании в системе (может отличаться от официального наименования компании', max_length=255, verbose_name='Наименование компании')),
                ('is_my_company', models.BooleanField(default=False, help_text='Признак компании, по которой ведется учет', verbose_name='Моя компания')),
                ('phone', models.CharField(help_text='Основной телефон компании', max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(help_text='Основная электронная почта компании', max_length=254, verbose_name='Электронная почта')),
                ('site', models.URLField(help_text='Сайт компании', verbose_name='Сайт')),
                ('requisites', models.OneToOneField(help_text='Реквизиты компании', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='companies.requisites', verbose_name='Реквизиты')),
                ('type', models.ForeignKey(help_text='Тип компании', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.companytype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': ('Компания',),
                'verbose_name_plural': 'Компании',
                'ordering': ['name'],
            },
        ),
    ]
