# Generated by Django 4.0.4 on 2022-05-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_requisites_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(help_text='Основная электронная почта компании', max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='company',
            name='site',
            field=models.URLField(help_text='Сайт компании', null=True, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='requisites',
            name='kpp',
            field=models.CharField(blank=True, help_text='Код причины постановки', max_length=10, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='requisites',
            name='ogrn',
            field=models.CharField(help_text='Основной государственный регистрационный номер компании', max_length=15, unique=True, verbose_name='ОГРН/ОГРНИП'),
        ),
    ]
