# Generated by Django 4.0.4 on 2022-06-01 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0005_alter_company_options_alter_companytype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Автоматически задается при создании', verbose_name='Дата и время создания')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Автоматически задается при изменении', verbose_name='Дата и время изменения')),
                ('date', models.DateField(help_text='Дата дохода', verbose_name='Дата')),
                ('summa', models.DecimalField(decimal_places=2, help_text='Сумма дохода в рублях', max_digits=12, verbose_name='Сумма')),
                ('company', models.ForeignKey(help_text='Контрагент операции', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': ('Доход',),
                'verbose_name_plural': ('Доходы',),
                'ordering': ['date', 'company'],
            },
        ),
    ]
