# Generated by Django 4.0.4 on 2022-06-02 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['date', 'company'], 'verbose_name': 'Доход', 'verbose_name_plural': 'Доходы'},
        ),
    ]
